name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '32 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [10.x]

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Generate Tweet image
      uses: r-lib/actions/setup-r@v1
    - name: Install Package Dependencies
      run: |-
        Rscript -e "install.packages('remotes')"
        Rscript -e "remotes::install_github('gadenbuie/tweetrmd')"
        Rscript -e "remotes::install_github('rstudio/webshot2')"
        Rscript -e "install.packages('rtweet')"
    - name: Generate tweet image
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
        run: |-
          Rscript -e "source('script.R')"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm ci
    - name: Update README
      env:
        MOKKAPPS_TOKEN: ${{ secrets.MOKKAPPS_TOKEN }}
      run: |-
        npm start
        cat README.md
    - name: Commit and push if README changed
      run: |-
        git diff
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"
        git diff --quiet || (git add README.md && git commit -m "Updated README")
        git push
